### PR TITLE
v2 beta to support react-navigation 2.3.1

### PR DESCRIPTION
**Pull request by ericvicenti**
react-navigation had a breaking change for redux users in v2.3.

Fortunately, this change makes the redux implementation more simple and robust.

Unfortunately, it will require a change for redux users. There are additional required arguments for createNavigationPropConstructor

### CODE REVIEW

**Comment by brentvatne** [comment]
can you update the `createNavigationPropConstructor` part of the readme as well?

**Comment by Ashoat** [comment]
Released! Thanks for the PR.

**Comment by ebitonte** [comment]
Hey @Ashoat @brentvatne and @ericvicenti - took me a bunch of time and research to realize that I had to upgrade react-navigation to ^2.3.0 when using this library on ^2.0.2. Can that get documented somewhere? Happy to make the PR myself, just wanted to check with y'all

**Comment by Ashoat** [comment]
@ebitonte: When using any library following the standard semver convention, you can expect that any major version update (eg. 1.2 -> 2.0) will have breaking changes. You can find release notes [here](https://github.com/react-navigation/react-navigation-redux-helpers/releases). Let me know if there are any other places you think having release notes would be helpful. The only place I don't want the release notes to be is the main README, since it'll just get more and more cluttered with notes that aren't relevant to new users.

**Comment by ebitonte** [comment]
Oh I'm sorry, had missed the release notes for 2.0.0 stating its dependency on `react-navigation@^2.3.0`. My misunderstanding, and thanks for the clarification. The breaking change being included in the semver minor update of react-navigation really threw me for a loop.

**Pull request merged**
